on:
  push:
    branches:
      - main
jobs:
#  test:
#    permissions:
#      contents: read
#      actions: read
#    uses: ./.github/workflows/ci.yml
#    secrets:
#      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  deploy:
#    needs: test
    permissions:
      contents: read
      actions: write
      packages: write
    uses: ./.github/workflows/cd.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
    with:
      APP_NAME: ${{ vars.APP_NAME }}
      # APP_NAME: protfolio-nextjs
      APP_PATH: ${{ vars.APP_PATH }}
      # APP_PATH: /home/altair823/portfolio-nextjs